---
title: "Diabetes Prevalence by State"
description: 
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages
library(tidyverse)
library(readxl)
library(rmarkdown)


```

```{r, include = FALSE, echo = FALSE}
CDI_data <- read_csv("CDI.csv")

```
```{r, echo = FALSE}
clean_d_data <- CDI_data %>% 
  filter(Question == "Prevalence of diagnosed diabetes among adults aged >= 18 years", Stratification1 == "Overall", DataValueType == "Age-adjusted Prevalence") %>% 
  drop_na(DataValueAlt) %>% 
  mutate(region = tolower(LocationDesc)) %>% 
  select(YearStart, region, Question, DataValueAlt, DataValueUnit)

map_data(map = "state") %>% 
  left_join(clean_d_data, by = "region") %>% 
  ggplot(mapping = aes(x = long, y = lat, group = group, fill = DataValueAlt)) +
  geom_polygon() +
  facet_wrap(~YearStart) +
  labs(title = "Prevalence of Diagnosed Diabetes among Adults by State",
       subtitle = "Higher prevalence of diabetes is seen in the southern region of the US",
       fill = "Age-adjusted\nPrevalence (%)",
       x = "Longitude",
       y = "Latitude")
```
```{r}
clean_dd_data <- CDI_data %>% 
  filter(Question == "Prevalence of depressive disorders among adults aged >= 18 years with diagnosed diabetes", 
         Stratification1 == "Overall", 
         DataValueType == "Age-adjusted Prevalence") %>% 
  drop_na(DataValueAlt) %>% 
  mutate(region = tolower(LocationDesc)) %>% 
  select(YearStart, region, Question, DataValueAlt, DataValueUnit)


map_data(map = "state") %>% 
  left_join(clean_dd_data, by = "region") %>% 
  ggplot(mapping = aes(x = long, y = lat, group = group, fill = DataValueAlt)) +
  geom_polygon() +
  facet_wrap(~YearStart) +
  labs(title = "Prevalence of Depressive Disorders among Adults Diagnosed\nwith Diabetes by State",
       subtitle = "Lower prevalence of depressive disorders among adults with diabetes\nis most consistently seen in California",
       fill = "Age-adjusted\nPrevalence (%)",
       x = "Longitude",
       y = "Latitude")
```

```{r}
clean_diabetes_data <- CDI_data %>% 
  mutate(diabetes = ifelse(str_detect(Question, "diabetes"), TRUE, FALSE)) %>% 
  filter(diabetes == TRUE,
         DataValueType == "Age-adjusted Rate",
         Stratification1 == "Overall",
         Question == "Mortality due to diabetes reported as any listed cause of death") %>% 
  drop_na(DataValueAlt) %>% 
  mutate(region = tolower(LocationDesc)) %>% 
  select(YearStart, region, Question, DataValueAlt, DataValueUnit) %>% 
  mutate(DataValueAlt = DataValueAlt/1000)

map_data(map = "state") %>% 
  left_join(clean_diabetes_data, by = "region") %>% 
  ggplot(mapping = aes(x = long, y = lat, group = group, fill = DataValueAlt)) +
  geom_polygon() +
  facet_wrap(~YearStart) +
  labs(title = "Mortality Rate due to Diabetes",
       subtitle = "Oklahoma consistently has the highest rates of mortality due to diabetes",
       fill = "Age-adjusted\nRate (%)",
       x = "Longitude",
       y = "Latitude")
  
```

